  name: Deploy TickerQ-Docs

  on:
    push:
      branches:
        - main
        
  permissions:
    contents: read
    packages: write

  jobs:
    build_and_deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to GHCR
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Build and push Docker image
          run: |
            OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            docker build -t ghcr.io/$OWNER/v8_tickerq_ui:latest .
            docker push ghcr.io/$OWNER/v8_tickerq_ui:latest

        - name: Trigger deploy
          run: curl -X POST -H "X-Deploy-Token:${{ secrets.DEPLOY_TOKEN }}" -H "Content-Type:application/json" -d '{"app":"v8_tickerq_ui"}'http://149.102.142.170:9000/hooks/deploy
